#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

NAME = CardinalMini
DPF_BUILD_DIR = ../../build/$(NAME)-sep
DSP_UI_SPLIT = true
MODGUI_CLASS_NAME = distrho_cardinal_mini
include ../Makefile.cardinal.mk
