#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

NAME = CardinalLoader
CARDINAL_VARIANT = loader
include ../Makefile.cardinal.mk

#ifndef CARDINAL_LOADER_IO
#define CARDINAL_LOADER_IO 2
#endif

#ifndef CARDINAL_LOADER_PARAMS
#define CARDINAL_LOADER_PARAMS 24
#endif
