#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

NAME = CardinalMini
PLUGIN_CLASS = distrho_cardinal_mini
PLUGIN_URI = https://distrho.kx.studio/plugins/cardinal\#mini
include ../Makefile.cardinal.mk
