#!/usr/bin/make -f
# Makefile for DISTRHO Plugins #
# ---------------------------- #
# Created by falkTX
#

NAME = CardinalMini
MODGUI_CLASS_NAME = distrho_cardinal_mini
include ../Makefile.cardinal.mk
